name: pasti_track
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  go_router: ^14.2.8
  firebase_auth: ^5.3.1
  share_plus: ^10.0.2
  dio: ^5.7.0
  flutter_local_notifications: ^17.2.3
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3
  path_provider: ^2.1.4
  flutter_bloc: ^8.1.6
  package_info_plus: ^8.0.2
  image_picker: ^1.1.2
  connectivity_plus: ^6.1.0
  intl: ^0.20.1
  timezone: ^0.9.4
  firebase_in_app_messaging: ^0.8.1
  flutter_launcher_icons: ^0.14.3
  workmanager: ^0.5.2
  provider: ^6.1.2
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  sqflite_common_ffi: ^2.3.4+4

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"
  android:
    generate: true
    min_sdk_android: 21
    adaptive_icon: true
    icon_size: 50 # min:48, max:256, default: 48
  ios:
    generate: true
  web:
    generate: true
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
