// Mocks generated by Mockito 5.4.4 from annotations
// in pasti_track/test/unit_tests/events/data/datasources/event_local_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pasti_track/core/database/db_local.dart' as _i3;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DBLocal].
///
/// See the documentation for Mockito's code generation for more information.
class MockDBLocal extends _i1.Mock implements _i3.DBLocal {
  MockDBLocal() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i4.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i4.Future<_i2.Database>);

  @override
  _i4.Future<int> insertUsuario(Map<String, dynamic>? usuario) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertUsuario,
          [usuario],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getUsuarios() => (super.noSuchMethod(
        Invocation.method(
          #getUsuarios,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>?> getUsuario(String? usuarioId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUsuario,
          [usuarioId],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<int> insertMedicament(Map<String, dynamic>? medicament) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertMedicament,
          [medicament],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getmedicines() => (super.noSuchMethod(
        Invocation.method(
          #getmedicines,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>?> getMedicamentById(String? medicamentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMedicamentById,
          [medicamentId],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<int> updateMedicament(
    String? id,
    Map<String, dynamic>? medicament,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMedicament,
          [
            id,
            medicament,
          ],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> deleteMedicament(String? medicamentId) => (super.noSuchMethod(
        Invocation.method(
          #deleteMedicament,
          [medicamentId],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> insertRoutine(Map<String, dynamic>? rutina) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertRoutine,
          [rutina],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getRoutines() => (super.noSuchMethod(
        Invocation.method(
          #getRoutines,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>?> getRutinaById(String? rutinaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRutinaById,
          [rutinaId],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<int> updateRoutine(
    String? id,
    Map<String, dynamic>? rutina,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRoutine,
          [
            id,
            rutina,
          ],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> deleteRoutine(String? rutinaId) => (super.noSuchMethod(
        Invocation.method(
          #deleteRoutine,
          [rutinaId],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getEventsByRoutine(
          String? routineId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByRoutine,
          [routineId],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAllEvents() => (super.noSuchMethod(
        Invocation.method(
          #getAllEvents,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getPendingEvents(
          DateTime? currentDate) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingEvents,
          [currentDate],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>?> getEventById(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventById,
          [eventId],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<int> insertEvent(Map<String, dynamic>? event) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertEvent,
          [event],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> updateEvent(Map<String, dynamic>? json) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEvent,
          [json],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> updateEventStatusAndDates({
    required String? eventId,
    required String? dateDone,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEventStatusAndDates,
          [],
          {
            #eventId: eventId,
            #dateDone: dateDone,
          },
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> deleteEvent(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #deleteEvent,
          [eventId],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> deleteEventsByRoutineId(String? routineId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteEventsByRoutineId,
          [routineId],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}
